#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

if (! file_exists(__DIR__ . '/vendor/autoload.php')) {
    require __DIR__ . '/standalone/sponsors_update.php';
    exit(StandaloneSponsorUpdater\run($argv));
}

require __DIR__ . '/vendor/autoload.php';

$app = require_once __DIR__ . '/bootstrap/app.php';

$status = $app->handleCommand(new Symfony\Component\Console\Input\ArgvInput());

exit($status);
