[supervisord]
nodaemon=true
[program:php-fpm]
command=php-fpm
[program:nginx]
command=nginx -g "daemon off;"
[program:queue]
command=php /var/www/html/artisan queue:work --tries=3 --timeout=120
[program:scheduler]
command=/bin/sh -c "while true; do php /var/www/html/artisan schedule:run; sleep 60; done"
